PARAMETER_TEXT_BODY     = 'text'
PARAMETER_TEXT_TITLE    = 'title'
PARAMETER_TEXT_TYPE     = 'type'
PARAMETER_TEXT_SOURCE   = 'source'
PARAMETER_CWSID         = 'cwsid'
PARAMETER_PARENT_CWSID  = 'parentcwsid'
PARAMETER_POSITION      = 'position'
PARAMETER_AI_ANSWER     = 'aianswer'
PARAMETER_QUESTION_ID   = 'questionid'
PARAMETER_SEARCH_WORD   = 'word'
PARAMETER_TEXT_FRAGMENT = 'fragment'
PARAMETER_JYUTPING      = 'jyutping'
PARAMETER_TERM          = 'term'
PARAMETER_DEFINITION    = 'definition'
PARAMETER_POINT1        = 'p1'
PARAMETER_POINT2        = 'p2'



CWS_TYPE_IMPORT_TEXT        = 100
CWS_TYPE_IMPORT_ARTICLE     = 110
CWS_TYPE_THROWAWAY          = 120

CWS_TYPE_AI_RESPONSE        = 200

CWS_TYPE_DIRECT_AI_ANALYZE          = 210
CWS_TYPE_DIRECT_AI_ANALYZE_GRAMMAR  = 220
CWS_TYPE_DIRECT_AI_SUMMARIZE        = 230
CWS_TYPE_DIRECT_AI_SIMPLIFY         = 240


CWS_TYPE_FRAGMENT           = 300

FRAGMENT_TYPE_PARAGRAPH     = 410
FRAGMENT_TYPE_SENTENCE      = 420
FRAGMENT_TYPE_PART          = 430
